config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from estatisticas_facebook.pages.views import PageListView

urlpatterns = [
    
    url(r'^$', PageListView.as_view(), name='home'),
#    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('estatisticas_facebook.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^pages/', include('estatisticas_facebook.pages.urls', namespace='pages')),
    url(r'^posts/', include('estatisticas_facebook.posts.urls', namespace='posts')),
    url(r'^tokens/', include('estatisticas_facebook.tokens.urls', namespace='tokens')),
    url(r'^faceusers/', include('estatisticas_facebook.faceusers.urls', namespace='faceusers')),
    url(r'^reactions/', include('estatisticas_facebook.reactions.urls', namespace='reactions')),
    url(r'^comments/', include('estatisticas_facebook.comments.urls', namespace='comments')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

estatisticas_facebook/pages/urls.py
from django.conf.urls import url

from estatisticas_facebook.pages.views import *

urlpatterns = [

    url(
        regex=r'^create/$',
        view= PageCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^detail/(?P<pk>[\w-]+)/$',
        view= PageDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^page/(?P<slug>[\w-]+)/$',
        view= PageListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^page/erase/(?P<id>\w+)/$',
        view= ErasePage,
        name='erase-page'
    ),
    url(
        regex=r'^page/',
        view= PageListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^page_insights/create/(?P<id>\w+)/$',
        view= PageInsightsCreateView,
        name='insights-create'
    ),

    url(
        regex=r'^page_insights/create/(?P<id>\w+)/(?P<since>[\w-]+)/$',
        view= PageInsightsCreateViewCron,
        name='insights-create'
    ),
    
    url(
        regex=r'^page_insights/(?P<id>\w+)/$',
        view= PageInsightsListView,
        name='insights-list'
    ),
    url(
        regex=r'^page_insights/erase-all/',
        view= eraseAllPageinsights,
        name='erase-all-insights'
    ),
    url(
        regex=r'^page/erase-all/',
        view= eraseAllPages,
        name='erase-all-pages'
    ),
    
    #url(r'^page/insights/$', PageInsightsListView.as_view()),
    
    #url(r'^page/index/(?P<slug>\w+)/$', PageListView.as_view()),
]

estatisticas_facebook/posts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='list'),
    url(r'^new/$', views.PostCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.PostDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.PostUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.PostDelete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/create/$', views.PostCreateView, name='create'),
    url(r'^(?P<pk>\d+)/list/$', views.PostList.as_view(), name='list'),
]

estatisticas_facebook/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

estatisticas_facebook/comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', ]

estatisticas_facebook/faceusers/forms.py
from django import forms
from .models import FaceUsers


class FaceUsersForm(forms.ModelForm):
    class Meta:
        model = FaceUsers
        fields = ['name', ]

estatisticas_facebook/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['name', ]

class PostCreateForm(forms.Form):
    since = forms.DateField()
    
    

estatisticas_facebook/comments/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import CommentForm
from .models import *
from django.http import HttpResponse, HttpResponseRedirect
from estatisticas_facebook.pages.models import Page


class CommentList(ListView):
    model = Comment
    paginate_by = 20


class CommentCreate(CreateView):
    model = Comment
    form_class = CommentForm
    success_url = reverse_lazy('comments:list')


class CommentDetail(DetailView):
    model = Comment


class CommentUpdate(UpdateView):
    model = Comment
    form_class = CommentForm
    success_url = reverse_lazy('comments:list')


class CommentDelete(DeleteView):
    model = Comment
    success_url = reverse_lazy('comments:list')


def CommentCreateView(request, **kwargs):

    getCommentInfo(Page.objects.get(id__iexact=kwargs['pk']))
    return HttpResponseRedirect(reverse('pages:detail',kwargs={'pk': kwargs['pk']}));
    

estatisticas_facebook/faceusers/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import FaceUsersForm
from .models import FaceUsers


class FaceUsersList(ListView):
    model = FaceUsers
    paginate_by = 20


class FaceUsersCreate(CreateView):
    model = FaceUsers
    form_class = FaceUsersForm
    success_url = reverse_lazy('faceusers:list')


class FaceUsersDetail(DetailView):
    model = FaceUsers


class FaceUsersUpdate(UpdateView):
    model = FaceUsers
    form_class = FaceUsersForm
    success_url = reverse_lazy('faceusers:list')


class FaceUsersDelete(DeleteView):
    model = FaceUsers
    success_url = reverse_lazy('faceusers:list')

estatisticas_facebook/pages/views.py
from django.shortcuts import render
from django.db.models.functions import Coalesce
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from estatisticas_facebook.pages.models import *
from estatisticas_facebook.posts.models import Post
from estatisticas_facebook.comments.models import Comment
from estatisticas_facebook.reactions.models import Reaction
from estatisticas_facebook.faceusers.models import FaceUsers
from util.graph import *
from django.db.models import Q

import facebook
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from .forms import *
from django.core.urlresolvers import reverse
from .tables import *
from django_tables2 import RequestConfig

# Create your views here.

class PageView(TemplateView):
    
    def get_context_data(self, *args, **kwargs):
        context = super(PageView, self).get_context_data(*args, **kwargs)
        return context

def eraseAllPageinsights(request):
    return eraseModelAndReturnHttpResponse(PageInsights)

def eraseAllPages(request):
    return eraseModelAndReturnHttpResponse(Page)

def eraseModelAndReturnHttpResponse(model):
    model.objects.all().delete()
    return HttpResponse("Quantidade de dados na tabela: "+str(model.objects.all().count()))

def ErasePage(request, id):
    Page.objects.get(id__iexact=id).delete()
    return HttpResponseRedirect(reverse('pages:list'));
    
class PageDetailView(DetailView):
   
    
    def get_context_data(self, **kwargs):
        context = super(PageDetailView, self).get_context_data(**kwargs)
        print(self.kwargs.get("pk"))
        context['page_insights'] = PageInsights.objects.filter(page__id__iexact=self.kwargs.get("pk")).count()
        context['posts'] = Post.objects.filter(page__id__iexact=self.kwargs.get("pk")).count()
        context['comments'] = Comment.objects.filter(post__page__id__iexact=self.kwargs.get("pk")).count()
        context['reactions'] = Reaction.objects.filter(post__page__id__iexact=self.kwargs.get("pk")).count()
        context['reactions_like'] = Reaction.objects.filter(post__page__id__iexact=self.kwargs.get("pk"), type="LIKE").count()
        context['reactions_love'] = Reaction.objects.filter(post__page__id__iexact=self.kwargs.get("pk"), type="LOVE").count()
        context['reactions_haha'] = Reaction.objects.filter(post__page__id__iexact=self.kwargs.get("pk"), type="HAHA").count()
        context['reactions_wow'] = Reaction.objects.filter(post__page__id__iexact=self.kwargs.get("pk"), type="WOW").count()
        context['reactions_sad'] = Reaction.objects.filter(post__page__id__iexact=self.kwargs.get("pk"), type="SAD").count()
        context['reactions_angry'] = Reaction.objects.filter(post__page__id__iexact=self.kwargs.get("pk"), type="ANGRY").count()
        context['faceusers'] = FaceUsers.objects.all().count()
        context['haters'] = FaceUsers.objects.all().order_by('-post_reactions_angry_total')[:10]
        context['likers'] = FaceUsers.objects.all().order_by('-post_reactions_like_total')[:10]
        context['lovers'] = FaceUsers.objects.all().order_by(Coalesce('post_reactions_love_total','comments').desc())[:10]
        context['sads'] = FaceUsers.objects.all().order_by(Coalesce('post_reactions_sad_total','comments').desc())[:10]
        context['commenters'] = FaceUsers.objects.all().order_by(Coalesce('comments','post_reactions_sad_total').desc())[:10]
        context['reactions_is_complete'] = "Completo"
        if Post.objects.all().exclude(reaction_paging = FINISHED).exists():
            context['reactions_is_complete'] = "Incompleto"
        context['comments_is_complete'] = "Completo"
        if Post.objects.all().exclude(comment_paging = FINISHED).exists():
            context['comments_is_complete'] = "Incompleto"
            
        print(context['reactions_like'])
        
        '''
        from estatisticas_facebook.posts.admin import PostResource
        dataset = PostResource().export()
        print (dataset.csv)    
        '''    
            
            
        return context
        
    def get_queryset(self):
        pk = self.kwargs.get("pk")
        if pk:
            queryset = queryset = Page.objects.filter(id__iexact=pk)
        else:
            queryset = Page.objects.all()
            
        return queryset

class PageListView(ListView):
    def get_queryset(self):
        print(self.kwargs)
        slug = self.kwargs.get("slug")
        if slug:
            queryset = queryset = Page.objects.filter(slug__iexact=slug)
        else:
            queryset = Page.objects.all()
        return queryset
    
    queryset = Page.objects.all()

class PageCreateView(CreateView):
    form_class = PageCreateForm
    template_name = 'pages/form.html'
    def get_success_url(self):
        return reverse('pages:detail',args=(self.object.id,))

def PageInsightsListView(request, id):
    template_name = 'pages/pageinsights_list.html'
    page_name = Page.objects.get(id__iexact = id).pretty_name

    queryset = PageInsights.objects.filter(Q(page__id__iexact=id))
    
    
    table = PageInsightsTable(queryset)

    RequestConfig(request).configure(table)
    
    return render(request, 'pages/pageinsights_list.html', {'table': table, 'page_name': page_name, 'id':id})


def PageInsightsCreateView(request, **kwargs):
    form = PageInsightsCreateForm(request.POST or None)
    template_name = 'pages/pageinsights_form.html'
    errors = None
    if form.is_valid():
        args = kwargs
        args['since'] = form.cleaned_data.get('since')
        getPageInsights(args)
        
        return HttpResponseRedirect(reverse('pages:detail',kwargs={'pk': kwargs['id']}));
    
    if form.errors:
        errors = form.errors
    
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)

class PageInsightsDetailView(DetailView):
    queryset = PageInsights.objects.all()

estatisticas_facebook/posts/views.py
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import PostForm, PostCreateForm
from .models import *
from util.graph import *
from estatisticas_facebook.pages.models import Page
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect


class PostList(ListView):
    model = Post
    paginate_by = 20


class PostCreate(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:list')


class PostDetail(DetailView):
    model = Post


class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:list')


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('posts:list')

def PostCreateView(request, **kwargs):
    form = PostCreateForm(request.POST or None)
    template_name = 'posts/post_form.html'
    errors = None
    if form.is_valid():
        args = kwargs
        args['since'] = form.cleaned_data.get('since')
        getPostInfo(Page.objects.get(id__iexact=kwargs['pk']),args['since'])
        
        return HttpResponseRedirect(reverse('pages:detail',kwargs={'pk': kwargs['pk']}));
    
    if form.errors:
        errors = form.errors
    
    context = {"form": form, "errors": errors}
    return render(request, template_name, context)

estatisticas_facebook/reactions/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import ReactionForm
from .models import *
from django.http import HttpResponse, HttpResponseRedirect


class ReactionList(ListView):
    model = Reaction
    paginate_by = 20


class ReactionCreate(CreateView):
    model = Reaction
    form_class = ReactionForm
    success_url = reverse_lazy('reactions:list')


class ReactionDetail(DetailView):
    model = Reaction


class ReactionUpdate(UpdateView):
    model = Reaction
    form_class = ReactionForm
    success_url = reverse_lazy('reactions:list')


class ReactionDelete(DeleteView):
    model = Reaction
    success_url = reverse_lazy('reactions:list')

def ReactionCreateView(request, **kwargs):

    getReactionInfo(Page.objects.get(id__iexact=kwargs['pk']))
    return HttpResponseRedirect(reverse('pages:detail',kwargs={'pk': kwargs['pk']}));
    

estatisticas_facebook/tokens/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import TokenForm
from .models import Token


class TokenList(ListView):
    model = Token
    paginate_by = 20


class TokenCreate(CreateView):
    model = Token
    form_class = TokenForm
    success_url = reverse_lazy('tokens:list')


class TokenDetail(DetailView):
    model = Token


class TokenUpdate(UpdateView):
    model = Token
    form_class = TokenForm
    success_url = reverse_lazy('tokens:list')


class TokenDelete(DeleteView):
    model = Token
    success_url = reverse_lazy('tokens:list')

estatisticas_facebook/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

estatisticas_facebook/templates/pages/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}Sobre{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">
        <H1>Política de privacidade</H1>
        <p>Este sistema tem como objetivo capturar informações sobre reações de posts no Facebook. 
        Ele coleta dados de análise de páginas que você possui permissão para coletar, 
        e os armazena para futura análise em um banco de dados.</p>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

estatisticas_facebook/templates/pages/form.1.html
{% extends "base.html" %}

{% block head_title %} 
    Pages | {{ block.super}}
{% endblock head_title %} 

{% block content %}
    <h2>Adicionar Página</h2>
    
    <form method='POST'>{% csrf_token %}
        <input class="form-control" type='text' name='name' placeholder="Slug da página"><br/>
        <input class="form-control" type='text' name='access_token' placeholder="Access Token"><br/>
        <input class="form-control" name='since' placeholder="Data (2016-12-31)" ><br/>
        <button class="btn" type='submit'>Salvar</button>
    </form>
    
{% endblock content %}

estatisticas_facebook/templates/pages/form.html
{% extends "base.html" %}

{% block head_title %} 
    Pages | {{ block.super}}
{% endblock head_title %} 

{% block content %}
    <h2>Adicionar Página</h2>
    
    <form method='POST'>{% csrf_token %}
        <input class="form-control" type='text' name='name' placeholder="Nome da página"><br/>
        <button class="btn" type='submit'>Salvar</button>
    </form>
    
{% endblock content %}

estatisticas_facebook/templates/pages/home.html
{% extends "base.html" %}

{% block head_title %} 
    Pages | {{ block.super}}
{% endblock head_title %} 

{% block content %}
    <ul>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'pages:list' %}">Exibir Páginas <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
    </ul>
{% endblock content %}

estatisticas_facebook/templates/pages/page_detail.html
{% extends "base.html" %}

{% block head_title %} 
    Pages | {{ block.super}}
{% endblock head_title %} 

{% block content %}

<h1>{{ object.pretty_name }}</h1>

<div class="row">
  <div class="col">
    <table class="table  table-sm table-striped">
    <tbody>
      <tr>
        <td><b>Short Name:</b></td>
        <td>{{ object.name }}</td>
      </tr>
      <tr>
        <td><b>Page Insights:</b></td>
        <td>{{ page_insights }}</a></td>
      </tr>
      <tr>
        <td><b>Posts:</b></td>
        <td>{{ posts }}(desde {{object.post_since.date}})</td>
      </tr>
      <tr>
        <td><b>Comentários:</b></td>
        <td>{{ comments }}({{comments_is_complete}})</td>
      </tr>
      <tr>
        <td><b>Reações:</b></td>
        <td>{{ reactions}}({{reactions_is_complete}})</td>
      </tr>
      <tr>
        <td><b>Reactions (Like) Total:</b></td>
        <td>{{ reactions_like}}</td>
      </tr>
      <tr>
        <td><b>Reactions (Love) Total:</b></td>
        <td>{{ reactions_love}}</td>
      </tr>
      <tr>
        <td><b>Reactions (Haha) Total:</b></td>
        <td>{{ reactions_haha}}</td>
      </tr>
      <tr>
        <td><b>Reactions (Wow) Total:</b></td>
        <td>{{ reactions_wow}}</td>
      </tr>
      <tr>
        <td><b>Reactions (Sad) Total:</b></td>
        <td>{{ reactions_sad}}</td>
      </tr>
      <tr>
        <td><b>Reactions (Angry) Total:</b></td>
        <td>{{ reactions_angry}}</td>
      </tr>
      <tr>
        <td><b>Usuários:</b></td>
        <td>{{ faceusers }}</td>
      </tr>
      <tr>
        <td><b>Top 10 angry:</b></td>
        <td>
          <ul>
          {% for hater in haters %}
              <li><a href="https://www.facebook.com/{{ hater.id}}">{{ hater.name}} ({{ hater.post_reactions_angry_total}})</a></li>
            {% endfor %}
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>Top 10 like:</b></td>
        <td>
          <ul>
          {% for liker in likers %}
              <li><a href="https://www.facebook.com/{{ liker.id}}">{{ liker.name}} ({{ liker.post_reactions_like_total}})</a></li>
            {% endfor %}
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>Top 10 love:</b></td>
        <td>
          <ul>
          {% for lover in lovers %}
              <li><a href="https://www.facebook.com/{{ lover.id}}">{{ lover.name}} ({{ lover.post_reactions_love_total}})</a></li>
            {% endfor %}
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>Top 10 sad:</b></td>
        <td>
          <ul>
          {% for sad in sads %}
              <li><a href="https://www.facebook.com/{{ sad.id}}">{{ sad.name}} ({{ sad.post_reactions_sad_total}})</a></li>
            {% endfor %}
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>Maiores commenters:</b></td>
        <td>
          <ul>
          {% for commenter in commenters %}
              <li><a href="https://www.facebook.com/{{ commenter.id}}">{{ commenter.name}} ({{ commenter.comments}})</a></li>
            {% endfor %}
          </ul>
        </td>
      </tr>
    
    </tbody>
    </table>
  </div>
  <div class="col">  

  </div>
</div>

<a href="{% url 'pages:insights-create' id=object.id %}" class="btn btn-info" role="button">Extrair insights</a>
<a href="{% url 'posts:create' pk=object.id %}" class="btn btn-info" role="button">Extrair Posts</a>
<a href="{% url 'reactions:create' pk=object.id %}" class="btn btn-info" role="button">Extrair Reações</a>
<a href="{% url 'comments:create' pk=object.id %}" class="btn btn-info" role="button">Extrair Comentários</a>

<a href="{% url 'pages:erase-page'      id=object.id %}" class="btn btn-danger" role="button">Apagar</a>

{% endblock content %}

estatisticas_facebook/templates/pages/page_home.html
{% extends "base.html" %}

{% block head_title %} 
    Pages | {{ block.super}}
{% endblock head_title %} 

{% block content %}
    <ul>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'pages:create' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
    </ul>
{% endblock content %}

estatisticas_facebook/templates/pages/page_list.html
{% extends "base.html" %}

{% block head_title %} 
    Pages | {{ block.super}}
{% endblock head_title %} 

{% block content %}
<h1>Páginas</h1>
<a href="{% url 'pages:create' %}" class="btn btn-info" role="button">Criar</a>

<table class="table  table-sm table-striped">
<tbody>
    {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'pages:detail' pk=obj.id %}"><p>{{ obj.pretty_name }}</p></a></td>
        </tr>
    {% endfor %}
</tbody>
</table>



{% endblock content %}

estatisticas_facebook/templates/pages/pageinsights_detail.html
{% extends "base.html" %}

{% block head_title %} PageInsights | {{ block.super}}{% endblock head_title %} 

{% block content %}
<h1>PageInsights</h1>
<ul>
    {{object.name}}
    {{object.page}}
    {{object.value}}
    {{object.end_time}}
    {{object.period}}
    {{object.title }}
    {{object.description }}
    {{object.name}}
    {{object.slug}}

</ul>

    {{ block.super }}
{% endblock content %}

estatisticas_facebook/templates/pages/pageinsights_form.html
{% extends "base.html" %}

{% block head_title %} 
    Pages | {{ block.super}}
{% endblock head_title %} 

{% block content %}
    <h2>Adicionar Página</h2>
    
    <form method='POST'>{% csrf_token %}
        <input class="form-control" name='since' placeholder="Data (2016-12-31)" ><br/>
        <button class="btn" type='submit'>Salvar</button>
    </form>
    
{% endblock content %}

estatisticas_facebook/templates/pages/pageinsights_list.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block head_title %} PageInsights | {{ block.super}}{% endblock head_title %} 

{% block content %}
<h2>PageInsights de {{page_name}}</h2>
<a href="{% url 'pages:detail' pk=id %}" class="btn btn-info" role="button">Voltar</a>
    {% render_table table %}
{% endblock content %}