config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from estatisticas_facebook.pages.views import PageListView

urlpatterns = [
    
    url(r'^$', PageListView.as_view(), name='home'),
#    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('estatisticas_facebook.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^pages/', include('estatisticas_facebook.pages.urls', namespace='pages')),
    url(r'^posts/', include('estatisticas_facebook.posts.urls', namespace='posts')),
    url(r'^tokens/', include('estatisticas_facebook.tokens.urls', namespace='tokens')),
    url(r'^faceusers/', include('estatisticas_facebook.faceusers.urls', namespace='faceusers')),
    url(r'^reactions/', include('estatisticas_facebook.reactions.urls', namespace='reactions')),
    url(r'^comments/', include('estatisticas_facebook.comments.urls', namespace='comments')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

estatisticas_facebook/reactions/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ReactionList.as_view(), name='list'),
    url(r'^new/$', views.ReactionCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.ReactionDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.ReactionUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.ReactionDelete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/create/$', views.ReactionCreateView, name='create'),
]

estatisticas_facebook/reactions/models.py
from django.core.urlresolvers import reverse
from django.db import models
from estatisticas_facebook.posts.models import *
from estatisticas_facebook.faceusers.models import *
from estatisticas_facebook.util.graph import *


QUERY = '/reactions?limit=100000'


def get_reactions(post):
    
    paged_query = get_paged_query(post.reaction_paging, QUERY)
    
    if paged_query:
        data = get_graph_object(post.page.id,post.id+paged_query)
    else:
        return

    get_item_and_paging(save_reaction_data, post, REACTIONS, data)

    get_reactions(post)
     
def getReactionInfo(page_model):
    
    from estatisticas_facebook.posts.models import Post
    post_list = Post.objects.filter(page = page_model).all()

    for post in post_list:
        if post.reaction_paging is not None and post.reaction_paging != FINISHED:
            get_reactions(post)

def get_user_object_from_reaction_json(reaction):
    user = {}
    user['name'] = reaction.get('name')
    user['id'] = reaction.get('id')
    return user

def save_reaction_data(post_model, data):

    for reaction in data:

        user = addInteraction(get_user_object_from_reaction_json(reaction), reaction.get('type'))
        
        Reaction(
            type = reaction.get('type'),
            user = user,
            post = post_model,
            ).save()
        #debug('new reaction saved: '+reaction.get('type'))


class Reaction(models.Model):
    type                                    = models.CharField(default="", max_length=64)
    user                                    = models.ForeignKey(FaceUsers, null=True)
    post                                    = models.ForeignKey('posts.Post', null=True, on_delete=models.CASCADE)
    name                                    = models.CharField(max_length = 512, default="")
    created                                 = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.type

    def get_absolute_url(self):
        return reverse('reactions:detail', args=[str(self.id)])

estatisticas_facebook/reactions/forms.py
from django import forms
from .models import Reaction


class ReactionForm(forms.ModelForm):
    class Meta:
        model = Reaction
        fields = ['name', ]

estatisticas_facebook/reactions/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import ReactionForm
from .models import *
from django.http import HttpResponse, HttpResponseRedirect


class ReactionList(ListView):
    model = Reaction
    paginate_by = 20


class ReactionCreate(CreateView):
    model = Reaction
    form_class = ReactionForm
    success_url = reverse_lazy('reactions:list')


class ReactionDetail(DetailView):
    model = Reaction


class ReactionUpdate(UpdateView):
    model = Reaction
    form_class = ReactionForm
    success_url = reverse_lazy('reactions:list')


class ReactionDelete(DeleteView):
    model = Reaction
    success_url = reverse_lazy('reactions:list')

def ReactionCreateView(request, **kwargs):

    getReactionInfo(Page.objects.get(id__iexact=kwargs['pk']))
    return HttpResponseRedirect(reverse('pages:detail',kwargs={'pk': kwargs['pk']}));
    

estatisticas_facebook/reactions/templates/reactions/reaction_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Apagar</h1>
    <p>Tem certeza que deseja apagar?</p>

    <form id="reaction_form" method="post" action=".">
    {% csrf_token %}
    <input type="submit" value="Sim" class="btn btn-primary" /> <a href="{% url 'reactions:list' %}" class="btn btn-danger">Não</a>
    </form>
{% endblock %}

estatisticas_facebook/reactions/templates/reactions/reaction_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Detalhes</h1>
    <p>{{ object.name }}</p>
    <a href="{% url 'reactions:list' %}">Lista</a>
{% endblock %}

estatisticas_facebook/reactions/templates/reactions/reaction_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
    <h1>Criar/Atualizar</h1>
    <form id="reaction_form" method="post" action="." class="form">
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Confirmar</button>
      {% endbuttons %}
    </form>
{% endblock %}

estatisticas_facebook/reactions/templates/reactions/reaction_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista</h1>
    <a href="{% url 'reactions:create' %}">Criar</a>
    <ul>
        {% for object in object_list %}
            <li>
                {{ object }}
                <a href="{{ object.get_absolute_url }}">Detalhes</a>
                <a href="{% url 'reactions:update' object.pk %}">Atualizar</a>
                <a href="{% url 'reactions:delete' object.pk %}">Apagar</a>
            </li>
        {% empty %}
                <p>Sem items.</p>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'reactions:list' %}?page={{ page_obj.previous_page_number }}">anterior</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'reactions:list' %}?page={{ page_obj.next_page_number }}">próximo</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}