config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from estatisticas_facebook.pages.views import PageListView

urlpatterns = [
    
    url(r'^$', PageListView.as_view(), name='home'),
#    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('estatisticas_facebook.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^pages/', include('estatisticas_facebook.pages.urls', namespace='pages')),
    url(r'^posts/', include('estatisticas_facebook.posts.urls', namespace='posts')),
    url(r'^tokens/', include('estatisticas_facebook.tokens.urls', namespace='tokens')),
    url(r'^faceusers/', include('estatisticas_facebook.faceusers.urls', namespace='faceusers')),
    url(r'^reactions/', include('estatisticas_facebook.reactions.urls', namespace='reactions')),
    url(r'^comments/', include('estatisticas_facebook.comments.urls', namespace='comments')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

estatisticas_facebook/faceusers/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.FaceUsersList.as_view(), name='list'),
    url(r'^new/$', views.FaceUsersCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.FaceUsersDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.FaceUsersUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.FaceUsersDelete.as_view(), name='delete'),
]

estatisticas_facebook/faceusers/models.py
from django.core.urlresolvers import reverse
from django.db import models
from estatisticas_facebook.util.graph import *

def getFaceUser(user_json):
    temp_user, created = FaceUsers.objects.get_or_create(id=user_json.get('id'))    
    temp_user.name = user_json.get('name')
    
    return temp_user

def setInteraction(model, interaction):
    interaction = interaction.lower()
    if interaction.lower() in ('like','love','wow','haha','sad','angry', 'pride','thankful'):
        model.reactions += 1
        attribute = 'post_reactions_'+interaction+'_total'
        value = getattr(model, attribute) + 1
        setattr(model, attribute, value)
    else:
        value = getattr(model, interaction) + 1
        setattr(model, interaction, value)
    
    #debug('new user interaction saved: '+interaction)

def addInteraction(user_json, interaction):
    face_user = getFaceUser(user_json)
    setInteraction(face_user, interaction)

    face_user.save()
    return face_user
    

class FaceUsers(models.Model):
    id                                      = models.CharField(primary_key = True, max_length = 45)
    name                                    = models.CharField(max_length = 450, default="")
    comments                                = models.IntegerField(default=0)
    shares                                  = models.IntegerField(default=0)
    reactions                               = models.IntegerField(default=0)
    post_reactions_like_total               = models.IntegerField(default=0)
    post_reactions_love_total               = models.IntegerField(default=0)
    post_reactions_wow_total                = models.IntegerField(default=0)
    post_reactions_haha_total               = models.IntegerField(default=0)
    post_reactions_sad_total                = models.IntegerField(default=0)
    post_reactions_angry_total              = models.IntegerField(default=0)
    post_reactions_pride_total              = models.IntegerField(default=0)
    post_reactions_thankful_total           = models.IntegerField(default=0)
    post_reactions_positivo_total           = models.IntegerField(default=0)
    post_reactions_negativo_total           = models.IntegerField(default=0)
    post_reactions_positivo_porcentagem     = models.IntegerField(default=0)
    post_reactions_negativo_porcentagem     = models.IntegerField(default=0)
    permalink_url                           = models.CharField(max_length = 450, default="")
    created                                 = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.id

    def get_absolute_url(self):
        return reverse('faceusers:detail', args=[str(self.id)])

estatisticas_facebook/faceusers/forms.py
from django import forms
from .models import FaceUsers


class FaceUsersForm(forms.ModelForm):
    class Meta:
        model = FaceUsers
        fields = ['name', ]

estatisticas_facebook/faceusers/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import FaceUsersForm
from .models import FaceUsers


class FaceUsersList(ListView):
    model = FaceUsers
    paginate_by = 20


class FaceUsersCreate(CreateView):
    model = FaceUsers
    form_class = FaceUsersForm
    success_url = reverse_lazy('faceusers:list')


class FaceUsersDetail(DetailView):
    model = FaceUsers


class FaceUsersUpdate(UpdateView):
    model = FaceUsers
    form_class = FaceUsersForm
    success_url = reverse_lazy('faceusers:list')


class FaceUsersDelete(DeleteView):
    model = FaceUsers
    success_url = reverse_lazy('faceusers:list')

estatisticas_facebook/faceusers/templates/faceusers/faceuser_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Apagar</h1>
    <p>Tem certeza que deseja apagar?</p>

    <form id="faceuser_form" method="post" action=".">
    {% csrf_token %}
    <input type="submit" value="Sim" class="btn btn-primary" /> <a href="{% url 'faceusers:list' %}" class="btn btn-danger">Não</a>
    </form>
{% endblock %}

estatisticas_facebook/faceusers/templates/faceusers/faceuser_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Detalhes</h1>
    <p>{{ object.name }}</p>
    <a href="{% url 'faceusers:list' %}">Lista</a>
{% endblock %}

estatisticas_facebook/faceusers/templates/faceusers/faceuser_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
    <h1>Criar/Atualizar</h1>
    <form id="faceuser_form" method="post" action="." class="form">
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Confirmar</button>
      {% endbuttons %}
    </form>
{% endblock %}

estatisticas_facebook/faceusers/templates/faceusers/faceuser_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista</h1>
    <a href="{% url 'faceusers:create' %}">Criar</a>
    <ul>
        {% for object in object_list %}
            <li>
                {{ object }}
                <a href="{{ object.get_absolute_url }}">Detalhes</a>
                <a href="{% url 'faceusers:update' object.pk %}">Atualizar</a>
                <a href="{% url 'faceusers:delete' object.pk %}">Apagar</a>
            </li>
        {% empty %}
                <p>Sem items.</p>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'faceusers:list' %}?page={{ page_obj.previous_page_number }}">anterior</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'faceusers:list' %}?page={{ page_obj.next_page_number }}">próximo</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}

estatisticas_facebook/faceusers/templates/faceusers/faceusers_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Apagar</h1>
    <p>Tem certeza que deseja apagar?</p>

    <form id="faceusers_form" method="post" action=".">
    {% csrf_token %}
    <input type="submit" value="Sim" class="btn btn-primary" /> <a href="{% url 'faceusers:list' %}" class="btn btn-danger">Não</a>
    </form>
{% endblock %}

estatisticas_facebook/faceusers/templates/faceusers/faceusers_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Detalhes</h1>
    <p>{{ object.name }}</p>
    <a href="{% url 'faceusers:list' %}">Lista</a>
{% endblock %}

estatisticas_facebook/faceusers/templates/faceusers/faceusers_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
    <h1>Criar/Atualizar</h1>
    <form id="faceusers_form" method="post" action="." class="form">
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Confirmar</button>
      {% endbuttons %}
    </form>
{% endblock %}

estatisticas_facebook/faceusers/templates/faceusers/faceusers_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista</h1>
    <a href="{% url 'faceusers:create' %}">Criar</a>
    <ul>
        {% for object in object_list %}
            <li>
                {{ object }}
                <a href="{{ object.get_absolute_url }}">Detalhes</a>
                <a href="{% url 'faceusers:update' object.pk %}">Atualizar</a>
                <a href="{% url 'faceusers:delete' object.pk %}">Apagar</a>
            </li>
        {% empty %}
                <p>Sem items.</p>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'faceusers:list' %}?page={{ page_obj.previous_page_number }}">anterior</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'faceusers:list' %}?page={{ page_obj.next_page_number }}">próximo</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}